# Questions

1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [4]:
#1 Write a Python Program to Add Two Matrices?

import numpy as np

a1=np.array([[2,3,4],[5,4,3]])
a2=np.array([[4,5,6],[5,6,7]])

a3=a1+a2
a3

array([[ 6,  8, 10],
       [10, 10, 10]])

In [18]:
#2 Write a Python Program to Multiply Two Matrices?
a3=np.array([[2,3,4],[5,4,3]])
a4=np.array([[4,5,6],[5,6,7],[6,7,8]])

a5=a3@a4
a5

array([[47, 56, 65],
       [58, 70, 82]])

In [29]:
#3 Write a Python Program to Transpose a Matrix?
a6=np.array([[4,5,6],[99,6,0],[67,98,43]])

a7=np.transpose(a6)
print(f"Before Transpose \n{a6}")
print(f"After Transpose \n{a7}")




Before Transpose 
[[ 4  5  6]
 [99  6  0]
 [67 98 43]]
After Transpose 
[[ 4 99 67]
 [ 5  6 98]
 [ 6  0 43]]


In [2]:
#4 Write a Python Program to Sort Words in Alphabetic Order?

a=input("Enter the string:\n")
l=[]
l=a.split(' ')
b=sorted(l)
alphabetical_order=''
for i in b:
    alphabetical_order=alphabetical_order+i+' '
    
print("String after arranging in alphabetical order:\n")    
print(alphabetical_order)
    


Enter the string:
tanmay is a good boy
String after arranging in alphabetical order:

a boy good is tanmay 


In [16]:
#5 Write a Python Program to Remove Punctuation From a String?
a=input("Enter a string with puncuations:\n")
New_string=""

for i in a:
    if i.isalpha()==True:
        New_string=New_string+i
    else:
        New_string=New_string+" "
        
print(f"New string without punctuation is: {New_string}")
        

Enter a string with puncuations:
Tanmay,ali*bhalu(kaifi > are valo players.
New string without punctuation is: Tanmay ali bhalu kaifi   are valo players 
