# Solutions:


Question 1: Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] Following are the fixed values of C and H: C is 50. H is 30. D is the variable whose values should be input to your program in a comma-separated sequence. Example Let us assume the following comma separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24

In [20]:
#1
c=50
h=30
f=1
string=""
s=input("Enter the input as mentioned in the question: \n")
l=list(s.split(','))
for d in l:
    s1=int(((2*c*int(d)/h)**0.5))
    string=string+str(s1)
    
    if f<len(l):
        string=string+','
        f=f+1
    else:
        break;
        
print(string)
        



Enter the input as mentioned in the question: 
100,150,180
18,22,24


Question 2: Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡Y-1. Example Suppose the following inputs are given to the program: 3,5 Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [39]:
#2 
import numpy as np

x=int(input("Enter X: "))
y=int(input("Enter Y: "))
matrix=np.zeros((x,y))

for i in range(x):
    for j in range(0,y):
        matrix[i][j]=i*j
        
print(matrix)
        
        

Enter X: 3
Enter Y: 5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


Question 3: Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program: without,hello,bag,world Then, the output should be: bag,hello,without,world

In [52]:
#3 
s=input("Enter the string as mentioned in the question: \n")
l=list(s.split(','))
string=''
f=1
for i in sorted(l):
    string=string+i
    if f<len(l):
        string=string+','
        f=f+1
    else:
        break
print("OUTPUT: ")        
print(string)
    
    


Enter the string as mentioned in the question: 
without,hello,bag,world
OUTPUT: 
bag,hello,without,world


Question 4: Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically. Suppose the following input is supplied to the program: hello world and practice makes perfect and hello world again Then, the output should be: again and hello makes perfect practice world

In [72]:
#4
s=input("Enter the string: ")
l=list(s.split(' '))
s2=set(l)

s1=""
for i in sorted(s2):
    s1=s1+i+' '

print()
print(s1)


Enter the string: hello world and practice makes perfect and hello world again

again and hello makes perfect practice world 


Question 5: Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program: hello world! 123 Then, the output should be: LETTERS 10

In [74]:
#5
s=input("Enter string: ")
l,d=0,0
for i in s:
    if i.isdigit():
        d=d+1
    elif i.isalpha():
        l=l+1
    else:
        pass
    
print(f"LETTERS: {l} \n")

print(f"DIGITS: {d}")


Enter string: hello world! 123
LETTERS: 10 

DIGITS: 3


Question 6: A website requires the users to input username and password to register. Write a program to check the validity of password input by users. Following are the criteria for checking the password:

At least 1 letter between [a-z]
At least 1 number between [0-9]
At least 1 letter between [A-Z]
At least 1 character from [$#@]
Minimum length of transaction password: 6
Maximum length of transaction password: 12 Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma. Example If the following passwords are given as input to the program: ABd1234@1,a F1#,2w3E*,2We3345 Then, the output of the program should be: ABd1234@1

In [20]:
#6
pw=input("Enter your passwords: ")
pw1=list(pw.split(','))
c1=0
c2=0
c3=0
c4=0
c5=0
sp_ch=['$','#','@']
for j in pw1:
    c1=0
    c2=0
    c3=0
    c4=0
    c5=0
    for i in j:
        if (i.isupper() and i.isalpha()):
            c1=c1+1
        if (i.islower() and i.isalpha()):
              c2=c2+1
        if (i.isnumeric()):
            c3=c3+1
        if(i in sp_ch):
            c4=c4+1
        if(len(j)>=6 and len(j)<=12):
            c5=c5+1
        else:
            pass
    if(c1>0 and c2>0 and c3>0 and c4>0 and c5>0):
        print(j+" ")
    else:
        c1=0
        c2=0
        c3=0
        c4=0
        c5=0
    
    




Enter your passwords: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1 
